local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: robot/base_footprint
      use_sim_time: True
      rolling_window: True
      width: 5
      height: 5
      resolution: 0.05
      robot_radius: 0.48 # 0.473126833
      plugins: [voxel_layer, inflation_layer]
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        cost_scaling_factor: 3.0
        inflation_radius: 0.5
      voxel_layer:
        plugin: nav2_costmap_2d::VoxelLayer
        enabled: True
        footprint_clearing_enabled: true
        max_obstacle_height: 3.0
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        unknown_threshold: 15
        mark_threshold: 3
        observation_sources: lidar3d_obstacles lidar3d_ground rgbd_obstacles rgbd_ground
        lidar3d_obstacles:
          topic: /lidar3d_obstacles
          max_obstacle_height: 3.0
          min_obstacle_height: 0.1
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          clearing: True
          marking: True
          data_type: PointCloud2
        lidar3d_ground:
          topic: /lidar3d_ground
          max_obstacle_height: 3.0
          min_obstacle_height: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          clearing: True
          marking: False
          data_type: PointCloud2
        rgbd_obstacles:
          topic: /rgbd_obstacles
          max_obstacle_height: 3.0
          min_obstacle_height: 0.1
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          clearing: True
          marking: True
          data_type: PointCloud2
        rgbd_ground:
          topic: /rgbd_ground
          max_obstacle_height: 3.0
          min_obstacle_height: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          clearing: True
          marking: False
          data_type: PointCloud2
      static_layer:
        plugin: nav2_costmap_2d::StaticLayer
        map_subscribe_transient_local: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: robot/base_footprint
      use_sim_time: True
      robot_radius: 0.48 # 0.473126833
      resolution: 0.05
      track_unknown_space: true
      plugins: [static_layer, inflation_layer]
      static_layer:
        plugin: nav2_costmap_2d::StaticLayer
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        cost_scaling_factor: 3.0
        inflation_radius: 0.5
      always_send_full_costmap: True
