controller_server:
  ros__parameters:
    use_sim_time: true
    odom_topic: /odom
    controller_frequency: 5.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: [progress_checker]
    controller_plugins: [FollowPath]

    # Progress Checker
    progress_checker:
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    # Goal Checker
    goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true

    # Controller Plugin
    FollowPath:
      plugin: teb_local_planner::TebLocalPlannerROS

      # General
      teb_autosize: 1.0
      dt_ref: 0.3
      dt_hysteresis: 0.1
      max_samples: 500
      min_samples: 3
      exact_arc_length: False
      feasibility_check_no_poses: 5
      feasibility_check_lookahead_distance: -1.0
      publish_feedback: False

      # Velocity
      max_vel_x: 0.7
      max_vel_x_backwards: 0.2
      max_vel_y: 0.0
      max_vel_theta: 1.0
      acc_lim_x: 3.2
      acc_lim_y: 0.5
      acc_lim_theta: 5.0

      # Thresholds
      min_obstacle_dist: 0.27
      inflation_dist: 0.5
      dynamic_obstacle_inflation_dist: 0.5

      # Obstacle Handling
      include_costmap_obstacles: True
      include_dynamic_obstacles: True
      obstacle_poses_affected: 30
      obstacle_cost_exponent: 4.0
      obstacle_heading_threshold: 0.45
      obstacle_keypoint_offset: 0.1
      costmap_obstacles_behind_robot_dist: 1.0
      legacy_obstacle_association: False
      obstacle_association_cutoff_factor: 5.0
      obstacle_association_force_inclusion_factor: 1.5
      obstacle_proximity_lower_bound: 0.0
      obstacle_proximity_upper_bound: 0.5
      obstacle_proximity_ratio_max_vel: 1.0

      # Optimization
      optimization_activate: True
      optimization_verbose: False
      no_inner_iterations: 5
      no_outer_iterations: 4
      penalty_epsilon: 0.1
      weight_max_vel_x: 20.0
      weight_max_vel_y: 0.0
      weight_max_vel_theta: 20.0
      weight_acc_lim_x: 1.0
      weight_acc_lim_y: 0.0
      weight_acc_lim_theta: 1.0
      weight_kinematics_nh: 10000.0
      weight_kinematics_forward_drive: 1000.0
      weight_kinematics_turning_radius: 1.0
      weight_optimaltime: 10.0 # must be > 0
      weight_shortest_path: 1.0
      weight_obstacle: 50.0
      weight_inflation: 0.5
      weight_dynamic_obstacle: 10.0 # not in use yet
      weight_dynamic_obstacle_inflation: 0.2
      weight_viapoint: 100.0
      weight_adapt_factor: 2.0
      weight_velocity_obstacle_ratio: 0.0
      weight_prefer_rotdir: 50.0

      # Footprint & Kinematics
      footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
        type: circular
        radius: 0.48 # 0.473126833
      wheelbase: 1.0
      min_turning_radius: 0.0
      cmd_angle_instead_rotvel: False
      is_footprint_dynamic: False
      length_start_orientation_vector: 0.4

      # Goal Behavior
      global_plan_overwrite_orientation: True
      allow_init_with_backwards_motion: False
      global_plan_prune_distance: 1.0
      global_plan_viapoint_sep: 0.5
      max_global_plan_lookahead_dist: 3.0
      free_goal_vel: false

      # Homotopy Class Planner
      enable_homotopy_class_planning: False
      enable_multithreading: True
      max_number_classes: 4
      selection_cost_hysteresis: 1.0
      selection_prefer_initial_plan: 1.0
      selection_obst_cost_scale: 1.0
      selection_alternative_time_cost: False
      selection_dropping_probability: 0.0
      selection_viapoint_cost_scale: 1.0
      simple_exploration: False
      roadmap_graph_no_samples: 15
      roadmap_graph_area_width: 6.0
      roadmap_graph_area_length_scale: 1.0
      h_signature_prescaler: 1.0
      h_signature_threshold: 0.1
      via_points_ordered: False
      viapoints_all_candidates: True
      delete_detours_backwards: True
      max_ratio_detours_duration_best_duration: 3.0
      switching_blocking_period: 0.0
      visualize_hc_graph: False
      visualize_with_time_as_z_axis_scale: 0.0

      # Recovery
      shrink_horizon_backup: True
      shrink_horizon_min_duration: 10.0
      oscillation_recovery: True
      oscillation_v_eps: 0.1
      oscillation_omega_eps: 0.1
      oscillation_recovery_min_duration: 10.0
      oscillation_filter_duration: 10.0

      # Costmap Converter
      costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
      costmap_converter_spin_thread: True
      costmap_converter_rate: 5
      costmap_model:
        scale: 1.0
        sum_scores: False

      # Reinitialization Behavior
      force_reinit_new_goal_dist: 1.0
      force_reinit_new_goal_angular: 1.5707963267948966

      # Divergence Detection (disabled by default)
      divergence_detection_enable: False
      divergence_detection_max_chi_squared: 10
