planner_server:
  ros__parameters:
    planner_plugin_types: [nav2_theta_star_planner/ThetaStarPlanner]
    planner_plugin_ids: [GridBased]
    GridBased:
      how_many_corners: 8
      w_euc_cost: 1.0
      w_traversal_cost: 2.0
