ekf_filter_node_odom:
  ros__parameters:
    qos_overrides:
      /odom:
        publisher:
          reliability: reliable
      /accel:
        publisher:
          reliability: reliable

    frequency: 30.0
    use_sim_time: false
    two_d_mode: true
    print_diagnostics: true
    debug: false
    permit_corrected_publication: false
    publish_acceleration: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: robot/base_footprint
    world_frame: odom

    odom0: /robot/robotnik_base_control/odom
    odom0_config:
      [
        false,
        false,
        false,

        false,
        false,
        false,

        true,
        false,
        false,

        false,
        false,
        true,

        false,
        false,
        false
      ]
    odom0_queue_size: 30
    odom0_differential: true
    odom0_relative: false

    odom1: /robot/zed2/zed_node/odom
    odom1_config:
      [
        true,
        true,
        false,

        false,
        false,
        false,

        true,
        true,
        false,

        false,
        false,
        false,

        false,
        false,
        false
      ]
    odom1_queue_size: 30
    odom1_differential: true
    odom1_relative: false

    imu0: /robot/zed2/zed_node/imu/data
    imu0_config:
      [
        false,
        false,
        false,

        false,
        false,
        true,

        false,
        false,
        false,

        false,
        false,
        false,

        false,
        false,
        false
      ]
    imu0_queue_size: 30
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true

    use_control: false

ekf_filter_node_map:
  ros__parameters:
    qos_overrides:
      /odom:
        publisher:
          reliability: reliable
      /accel:
        publisher:
          reliability: reliable

    frequency: 30.0
    use_sim_time: false
    two_d_mode: true
    print_diagnostics: true
    debug: false
    permit_corrected_publication: false
    publish_acceleration: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: robot/base_footprint
    world_frame: map

    odom0: local_odom
    odom0_config:
      [
        false,
        false,
        false,

        false,
        false,
        false,

        true,
        true,
        false,

        false,
        false,
        false,

        false,
        false,
        false
      ]
    odom0_queue_size: 30
    odom0_differential: false
    odom0_relative: false

    odom1: gps_odom
    odom1_config:
      [
        true,
        true,
        false,

        false,
        false,
        false,

        false,
        false,
        false,

        false,
        false,
        false,

        false,
        false,
        false
      ]
    odom1_queue_size: 30
    odom1_differential: false
    odom1_relative: false

    imu0: /robot/zed2/zed_node/imu/data
    imu0_config:
      [
        false,
        false,
        false,

        false,
        false,
        true,

        false,
        false,
        false,

        false,
        false,
        true,

        false,
        false,
        false
      ]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 30
    imu0_remove_gravitational_acceleration: true

    use_control: false

navsat_transform:
  ros__parameters:
    frequency: 30.0
    use_sim_time: false
    delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: true
    wait_for_datum: false
