imu_compass_node:
  ros__parameters:
    use_sim_time: false
    base_link_frame: "robot/base_link"
    compass:
      sensor_timeout: 0.5
      yaw_meas_variance: 10.0
      gyro_meas_variance: 0.01
      mag_declination: 0.0
    mag_bias:
      x: 9.215316949225336e-07
      y: -4.343107452318427e-07
      z: -1.0796713441654357e-06
      radius: 1.5142832612763405e-06
